# Generated by Django 6.0.5 on 2026-05-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilllisting',
            name='post_type',
            field=models.CharField(choices=[('offer', 'Offer'), ('wanted', 'Wanted')], default='offer', max_length=20),
        ),
    ]
